### PR TITLE
Format export JSON

### PR DESCRIPTION
**Pull request by ypconstante**

### CODE REVIEW

**Comment by piroor** [comment]
Could you describe why this cange is required? Extracting changed values looks meaningful to minify the exported data. On the other hand, this change will increases the size of the exported data, and pretty printed appearance looks unnecessary to import/export. (If you need to see pretty printed data, there are some alternatives: `jq` command, the developer console of Firefox itself, and more.)

**Comment by ypconstante** [comment]
In my case I use the export to create backups of the addons config and to make it easier to share then between computers, and I'm putting this configs in gist.
With the JSON formatted it's possible to check the diff between versions. It also seems to be kind of a standard to export a formatted JSON, I exported my stylus, uBlock and uMatrix configs, and the generated JSON comes formatted.

**Comment by piroor** [comment]
Thank you for explanation. Then, the important point of this change looks "uniform the format of exported data to other addons" and I think it is enough reasonable to merge.

**Comment by piroor** [comment]
Thanks again!

**Pull request merged**
